<?php

namespace App\Services;

class UserData
{
    public array $mainCategories = [
        "Graphics & Design",
        "Digital Marketing",
        "Writing & Translations",
        "Vidéos & Animations",
        "Music & Audio",
        "Programming & Tech",
        "Data",
        "Business",
        "Lifestyle",
    ];

    public array $subCategories = [
        "Graphics & Design" => [
            "Logo & Brand Identity",
            "Gaming",
            "Art & Illustration",
            "Web & App Design",
            "Social Media",
            "Packaging & Labels",
            "Visual Design",
            "Architecture & Building Design",
            "Fashion & Merchandise",
            "Print Design",
            "Product & Characters Design",
            "Misc",
        ],
        "Digital Marketing" => [
            "Social Media Marketing",
            "Social Media Advertising",
            "Search Engine Optimization (SEO)",
            "Local SEO",
            "Marketing Strategy",
            "Public Relations",
            "Content Marketing",
            "Video Marketing",
            "Email Marketing",
            "Web Analytics",
            "Crowdfunding",
            "Text Message Marketing",
            "Search Engine Marketing",
            "Display Advertising",
            "E-Commerce Marketing",
            "Influencer Marketing",
            "Community Management",
            "Mobile App Marketing",
            "Music Promotion",
            "Book & eBook Marketing",
            "Affiliate Marketing",
            "Podcast Marketing",
            "Other",
        ],
        "Writing & Translations" => [
            "Articles & Blog Posts",
            "Translation",
            "Proofreading & Editing",
            "Resume Writing",
            "Cover Letters",
            "LinkedIn Profiles",
            "Ad Copy",
            "Sales Copy",
            "Social Media Copy",
            "Email Copy",
            "Case Studies",
            "Book & eBook Writing",
            "Book Editing",
            "Scriptwriting",
            "Podcast Writing",
            "Beta Reading",
            "Creative Writing",
            "Brand Voice & Tone",
            "UX Writing",
            "Speechwriting",
            "eLearning Content Development",
            "White Papers",
            "Website Content",
            "Product Descriptions",
            "Press Releases",
            "Business Names & Slogans",
            "Technical Writing",
            "Legal Writing",
            "Grant Writing",
            "Transcripts",
            "Research & Summaries",
            "Oher",
        ],
        "Vidéos & Animations" => [
            "Whiteboard & Animated Explainers",
            "Video Editing",
            "Short Video Ads",
            "Lyric & Music Videos",
            "Character Animation",
            "Logo Animation",
            "Animated GIFs",
            "App & Website Previews",
            "Subtitles & Captions",
            "E-Commerce Product Videos",
            "Spokesperson Videos",
            "Live Action Explainers",
            "3D Product Animation",
            "Visual Effects",
            "Unboxing Videos",
            "Slideshow Videos",
            "eLearning Video Production",
            "Screencasting Videos",
            "Article to Video",
            "Animation for Kids",
            "Intros & Outros",
            "Animation for Streamers",
            "Lottie & Website Animation",
            "Game Trailers",
            "Book Trailers",
            "Drone Videography",
            "Real Estate Promos",
            "Product Photography",
            "Local Photography",
            "Other",
        ],
        "Music & Audio" => [
            "Voice Over",
            "Producers & Composers",
            "Singers & Vocalists",
            "Mixing & Mastering",
            "Session Musicians",
            "Online Music Lessons",
            "Podcast Editing",
            "Songwriters",
            "Beat Making",
            "Audiobook Production",
            "Audio Ads Production",
            "Sound Design",
            "Jingles & Intros",
            "Dialogue Editing",
            "Music Transcription",
            "Vocal Tuning",
            "DJ Drops & Tags",
            "DJ Mixing",
            "Remixing & Mashups",
            "Synth Presets",
            "Meditation Music",
            "Other",
        ],
        "Programming & Tech" => [
            "WordPress",
            "Website Builders & CMS",
            "Game Development",
            "Development for Streamers",
            "Web Programming",
            "E-Commerce Development",
            "Mobile Apps",
            "Desktop Applications",
            "Support & IT",
            "Get Your Website in a Few Steps",
            "Chatbots",
            "Online Coding Lessons",
            "Cybersecurity & Data Protection",
            "Convert Files",
            "User Testing",
            "QA & Review",
            "Other",
        ],
        "Data" => [
            "Databases",
            "Data Processing",
            "Data Analytics",
            "Data Visualization",
            "Data Science",
            "Data Entry",
            "Other",
        ],
        "Business" => [
            "Virtual Assistant",
            "Market Research",
            "Customer Care",
            "Project Management",
            "Business Consulting",
            "Business Plans",
            "Presentations",
            "Lead Generation",
            "Game Concept Design",
            "Legal Consulting",
            "Financial Consulting",
            "E-Commerce Management",
            "Supply Chain Management",
            "HR Consulting",
            "Career Counseling",
            "Flyer Distribution",
            "Other",
        ],
        "Lifestyle" => [
            "Online Tutoring",
            "Gaming",
            "Astrology & Psychics",
            "Modeling & Acting",
            "Traveling",
            "Health, Nutrition & Fitness",
            "Fitness Lessons",
            "Dance Lessons",
            "Life Coaching",
            "Greeting Cards & Videos",
            "Personal Stylists",
            "Cooking Lessons",
            "Craft Lessons",
            "Arts & Crafts",
            "Family & Genealogy",
            "Your Message On...",
            "Collectibles",
            "Other",
        ]
    ];

    public array $language = [
        'English',
        'Hindi',
        'Spanish',
        'German',
        'Arabic',
        'Italian',
        'Dutch',
        'Javanese',
        'Ukrainian',
        'Urdu',
        'French',
        'Bengali',
        'Punjabi',
        'Gujarati',
        'Chinese',
        'Russian',
        'Hebrew',
        'Vietnamese'
    ];

    public array $hourlyRate = [
        "less than 10$ per hour",
        "less than 20$ per hour",
        "more than 20$ per hour",
    ];
}
